apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: default
spec:
  secretName: nginx-cert
  dnsNames:
  - tejashwi.qzz.io
  - www.tejashwi.qzz.io
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
